import { HOTMART_PRAYER_REQUEST_PAYMENT_URL, PRAYER_REQUEST_PAYMENT_URL } from '@/shared/config/external-links';

export const PRAYER_REQUEST_PRODUCT_ID = 'pedido-oracion-personalizado';
export const PRAYER_REQUEST_DEFAULT_GOAL = 'general';
export const PRAYER_REQUEST_PAYMENT_LINK = PRAYER_REQUEST_PAYMENT_URL;
export const PRAYER_REQUEST_FALLBACK_PAYMENT_LINK = HOTMART_PRAYER_REQUEST_PAYMENT_URL;
